//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClientV2.ServiceA2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/08", ConfigurationName="ServiceA2.ServiceAContract")]
    public interface ServiceAContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/08/ServiceAContract/Operation1", ReplyAction="http://www.thatindigogirl.com/samples/2006/08/ServiceAContract/Operation1Response" +
            "")]
        string Operation1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/08/ServiceAContract/Operation2", ReplyAction="http://www.thatindigogirl.com/samples/2006/08/ServiceAContract/Operation2Response" +
            "")]
        string Operation2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/08/ServiceAContract/Operation3", ReplyAction="http://www.thatindigogirl.com/samples/2006/08/ServiceAContract/Operation3Response" +
            "")]
        string Operation3();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAContractChannel : WinClientV2.ServiceA2.ServiceAContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAContractClient : System.ServiceModel.ClientBase<WinClientV2.ServiceA2.ServiceAContract>, WinClientV2.ServiceA2.ServiceAContract {
        
        public ServiceAContractClient() {
        }
        
        public ServiceAContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Operation1() {
            return base.Channel.Operation1();
        }
        
        public string Operation2() {
            return base.Channel.Operation2();
        }
        
        public string Operation3() {
            return base.Channel.Operation3();
        }
    }
}
