//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunClient.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectProjectByUser", ReplyAction="http://tempuri.org/IService/SelectProjectByUserResponse")]
        System.Data.DataTable SelectProjectByUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectDeviceByProject", ReplyAction="http://tempuri.org/IService/SelectDeviceByProjectResponse")]
        System.Data.DataTable SelectDeviceByProject(string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectSensorByProject", ReplyAction="http://tempuri.org/IService/SelectSensorByProjectResponse")]
        System.Data.DataTable SelectSensorByProject(string projectName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : YunClient.localhost.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<YunClient.localhost.IService>, YunClient.localhost.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SelectProjectByUser(string userName) {
            return base.Channel.SelectProjectByUser(userName);
        }
        
        public System.Data.DataTable SelectDeviceByProject(string projectName) {
            return base.Channel.SelectDeviceByProject(projectName);
        }
        
        public System.Data.DataTable SelectSensorByProject(string projectName) {
            return base.Channel.SelectSensorByProject(projectName);
        }
    }
}
