//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunClient.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectProjectByUser", ReplyAction="http://tempuri.org/IService/SelectProjectByUserResponse")]
        System.Data.DataTable SelectProjectByUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectDeviceByProject", ReplyAction="http://tempuri.org/IService/SelectDeviceByProjectResponse")]
        System.Data.DataTable SelectDeviceByProject(string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectSensorByProject", ReplyAction="http://tempuri.org/IService/SelectSensorByProjectResponse")]
        System.Data.DataTable SelectSensorByProject(string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectProject", ReplyAction="http://tempuri.org/IService/SelectProjectResponse")]
        System.Data.DataTable SelectProject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectUnitByProject", ReplyAction="http://tempuri.org/IService/SelectUnitByProjectResponse")]
        System.Data.DataTable SelectUnitByProject(string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectProjectSensorByProjectUnit", ReplyAction="http://tempuri.org/IService/SelectProjectSensorByProjectUnitResponse")]
        System.Data.DataTable SelectProjectSensorByProjectUnit(int projectUnitID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectChannelSensorByProjectDevice", ReplyAction="http://tempuri.org/IService/SelectChannelSensorByProjectDeviceResponse")]
        System.Data.DataTable SelectChannelSensorByProjectDevice(int projectDeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectUser", ReplyAction="http://tempuri.org/IService/SelectUserResponse")]
        System.Data.DataTable SelectUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectDevice", ReplyAction="http://tempuri.org/IService/SelectDeviceResponse")]
        System.Data.DataTable SelectDevice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectSensor", ReplyAction="http://tempuri.org/IService/SelectSensorResponse")]
        System.Data.DataTable SelectSensor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SelectUnit", ReplyAction="http://tempuri.org/IService/SelectUnitResponse")]
        System.Data.DataTable SelectUnit();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : YunClient.localhost.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<YunClient.localhost.IService>, YunClient.localhost.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SelectProjectByUser(string userName) {
            return base.Channel.SelectProjectByUser(userName);
        }
        
        public System.Data.DataTable SelectDeviceByProject(string projectName) {
            return base.Channel.SelectDeviceByProject(projectName);
        }
        
        public System.Data.DataTable SelectSensorByProject(string projectName) {
            return base.Channel.SelectSensorByProject(projectName);
        }
        
        public System.Data.DataTable SelectProject() {
            return base.Channel.SelectProject();
        }
        
        public System.Data.DataTable SelectUnitByProject(string projectName) {
            return base.Channel.SelectUnitByProject(projectName);
        }
        
        public System.Data.DataTable SelectProjectSensorByProjectUnit(int projectUnitID) {
            return base.Channel.SelectProjectSensorByProjectUnit(projectUnitID);
        }
        
        public System.Data.DataTable SelectChannelSensorByProjectDevice(int projectDeviceID) {
            return base.Channel.SelectChannelSensorByProjectDevice(projectDeviceID);
        }
        
        public System.Data.DataTable SelectUser() {
            return base.Channel.SelectUser();
        }
        
        public System.Data.DataTable SelectDevice() {
            return base.Channel.SelectDevice();
        }
        
        public System.Data.DataTable SelectSensor() {
            return base.Channel.SelectSensor();
        }
        
        public System.Data.DataTable SelectUnit() {
            return base.Channel.SelectUnit();
        }
    }
}
